cifar10:
  module: modules.CAM.class_activation_map
  name: ClassActivationMap
  ClassActivationMap:
    model_config:
      module: models.definitions.resnet18
      name: Resnet18
      Resnet18:
        num_classes: 10
    classes:
      - airplane
      - automobile
      - bird
      - cat
      - deer
      - dog
      - frog
      - horse
      - ship
      - truck
    image_size: (224, 224)
    weight_path: '''models/weights/cifar10/resnet18_3.pt'''
    mean: '(0.485, 0.456, 0.406)'
    std: '(0.229, 0.224, 0.225)'
    device: '''cpu'''
