cifar_10:
  module: application.prediction.predictor
  name: Predictor
  Predictor:
    model_config:
      module: models.definitions.resnet18
      name: Resnet18
      Resnet18:
        num_classes: 10
    classes:
      0: airplane
      1: automobile
      2: bird
      3: cat
      4: deer
      5: dog
      6: frog
      7: horse
      8: ship
      9: truck
    image_size: (224, 224)
    batch_size: 1
    weight_path: '''models/weights/cifar10/resnet18_3.pt'''
    device: '''cpu'''
