train_dataset:
  module: dataloader.hymenoptera_dataset
  class: HymenopteraDataset
  HymenopteraDataset:
    dirname: '''dataset/hymenoptera/train'''
    pattern: '''**/*.jpg'''
    image_size: '(224, 224)'
    classes:
      ants: 0
      bees: 1
    mean: ['0.485', '0.456', '0.406']
    std: ['0.229', '0.224', '0.225']
    transforms:
      - 'torchvision.transforms.RandomVerticalFlip(p=0.5)'
    #   - 'torchvision.transforms.RandomRotation(degrees=(-45, 45), expand=True)'
    #   - 'torchvision.transforms.RandomGrayscale(p=0.5)'

train_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: True
    batch_size: 64

train_eval_dataset:
  module: dataloader.hymenoptera_dataset
  class: HymenopteraDataset
  HymenopteraDataset:
    dirname: '''dataset/hymenoptera/train'''
    pattern: '''**/*.jpg'''
    image_size: (224, 224)
    classes:
      0: ants
      1: bees
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

train_eval_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: False
    batch_size: 64

model:
  module: model.mobile_net_v2
  class: MobileNetV2
  MobileNetV2:
    num_classes: 2
    pretrained: True
    features_fixed: False

optimizer:
  module: torch.optim
  class: SGD
  SGD:
    lr: 0.01
    momentum: 0.02

loss:
  module: torch.nn
  class: CrossEntropyLoss

accuracy:
  module: metric.accuracy
  class: Accuracy
  Accuracy:
    topk: '(1,)'

lr_scheduler:
  module: torch.optim.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    mode: '''min'''
    factor: 0.1
    patience: 5
    eps: '1e-8'
    verbose: True
    cooldown: 0
    min_lr: 0

trainer:
  module: engine.engine
  class: TrainEpoch

evaluator:
  module: engine.engine
  class: EvalEpoch
